name: NeyKickAnim
version: '${project.version}'
author: Ney
main: org.ney.neykickanim.NeyKickAnim
api-version: 1.16
permissions:
  neykick.use:
    default: op
commands:
  neykick:
    permission: neykick.use